FROM continuumio/miniconda3:22.11.1

# install required dependencies
# RUN apt-get update -q && apt-get install -y build-essential

# v0.7
RUN apt-get update -q && apt-get install -y bc
# RUN pip install scutls==0.2.6

# v0.8
RUN pip install scutls==0.2.7


