FROM continuumio/miniconda3:23.3.1-0

RUN conda install -c bioconda samtools

RUN conda install -c conda-forge biopython

RUN conda install -c conda-forge regex

RUN conda install -c conda-forge matplotlib

RUN conda install -c anaconda pandas

RUN conda install -c bioconda bwa