# Adding GPU support, not finished yet.

## build a base miniconda3 image based on Xenial
## adapted from: https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/debian/Dockerfile

FROM ubuntu:16.04

LABEL maintainer="Kai Hu@UMMS"

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# hadolint ignore=DL3008
RUN apt-get update -q && \
    apt-get install -q -y --no-install-recommends \
        bzip2 \
        ca-certificates \
        git \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender1 \
        mercurial \
        subversion \
        wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH /opt/conda/bin:$PATH

CMD [ "/bin/bash" ]

# Leave these args here to better use the Docker build cache
ARG CONDA_VERSION=py38_4.9.2
ARG CONDA_MD5=122c8c9beb51e124ab32a0fa6426c656

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh -O miniconda.sh && \
    echo "${CONDA_MD5}  miniconda.sh" > miniconda.md5 && \
    if ! md5sum --status -c miniconda.md5; then exit 1; fi && \
    mkdir -p /opt && \
    sh miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh miniconda.md5 && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
    /opt/conda/bin/conda clean -afy

# add curl
RUN apt-get update -q && \
    apt-get install -q -y --no-install-recommends \
            curl \
            make

# add build essentials
RUN apt-get update -q && \
    apt-get install -q -y --no-install-recommends \
            build-essential \
            libz-dev \
            libbz2-dev \
            liblzma-dev

# add bonito:
RUN pip install --upgrade pip
RUN pip install ont-bonito
RUN pip install --extra-index-url https://download.pytorch.org/whl/cu113 ont-bonito

# add DNAscent: https://github.com/MBoemo/DNAscent/tree/3.1.2
RUN git clone --recursive https://github.com/MBoemo/DNAscent.git && \
    cd DNAscent && git checkout 3.1.2 && make
ENV PATH /DNAscent/bin:$PATH


# to enable GPU support: test not pass yet
# ref1: https://www.tensorflow.org/install/pip#install_cuda_with_apt
# ref2: https://www.tensorflow.org/install/pip#install_cuda_with_apt
# ref3: https://pythonspeed.com/articles/activate-conda-dockerfile/
RUN conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
# will not work, use the export solution below
RUN python3 -m pip install tensorflow
RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:\$CONDA_PREFIX/lib/" >> ~/.bashrc
